name: Xcode

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      env:
        THEMOVIEDB_API_KEY: ${{ secrets.THEMOVIEDB_API_KEY }}
      run: |
        export TMDB_API_TOKEN=$THEMOVIEDB_API_KEY
        make
        xcodebuild clean test -workspace Moviehub.xcworkspace -scheme Moviehub -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
        
